# fly.toml app configuration file generated for long-voice-9083 on 2023-10-04T22:15:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "long-voice-9083"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
